#!/usr/bin/env bash

set -e

source poky/oe-init-build-env $PWD/out

bitbake-layers show-layers

bitbake h4server-image

tree tmp/deploy/images/odroid-h4

wic create mkefidisk -e h4server-image

# bitbake bmap-tools-native -caddto_recipe_sysroot
# oe-run-native bmap-tools-native bmaptool copy mkefidisk-201804191017-sda.direct /dev/sdX

# sudo dd if=mkefidisk-201804191017-sda.direct of=/dev/sdX status=progress

exit 0
