#!/usr/bin/env bash

set -e

source poky/oe-init-build-env $PWD/out

bitbake-layers show-layers

bitbake h4server-image

tree tmp/deploy/images/odroid-h4

echo "RUN THIS: sudo dd if=tmp/deploy/images/odroid-h4/h4server-image-odroid-h4.wic of=/dev/sdX status=progress && sudo sync"

exit 0
